import { View, useWindowDimensions, ScrollView } from 'react-native'
import React, { useState } from 'react'
import { TabView, SceneMap, TabBar } from 'react-native-tab-view'
import { Flex, Text } from 'native-base'

const ProjectScreen = () => {
  const layout = useWindowDimensions()

  const [index, setIndex] = useState(0)
  const [routes] = useState([
    { key: 'first', title: '募集中' },
    { key: 'second', title: '進行中' },
    { key: 'third', title: '終了' },
  ])

  const FirstRoute = () => (
    <ScrollView style={{ flex: 1 }}>
      <Flex direction='column' p='24px'>
        <Flex
          w='100%'
          h='226px'
          backgroundColor='gray.300'
          borderRadius='16px'
          position='relative'
          shadow={2}
          mb='32px'
        >
          <Flex
            w='84px'
            py='10px'
            bg='#684EBD'
            direction='row'
            justifyContent='center'
            top='18px'
            borderRightRadius='8px'
            _text={{
              color: 'white',
            }}
          >
            募集期間
          </Flex>
        </Flex>
        <Flex w='100%' rounded='xl' mb='16px'>
          <Text fontSize='20px' bold alignSelf='flex-start' mb='16px'>
            サービス・アプリ開発
          </Text>
          <ScrollView horizontal>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
          </ScrollView>
        </Flex>
        <Flex w='100%' rounded='xl' mb='16px'>
          <Text fontSize='20px' bold alignSelf='flex-start' mb='16px'>
            ゲーム開発
          </Text>
          <ScrollView horizontal>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
          </ScrollView>
        </Flex>
        <Flex w='100%' rounded='xl' mb='16px'>
          <Text fontSize='20px' bold alignSelf='flex-start' mb='16px'>
            デザイン・イラスト
          </Text>
          <ScrollView horizontal>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
          </ScrollView>
        </Flex>
      </Flex>
    </ScrollView>
  )

  const SecondRoute = () => (
    <ScrollView style={{ flex: 1 }}>
      <Flex direction='column' p='24px'>
        <Flex
          w='100%'
          h='226px'
          backgroundColor='gray.300'
          borderRadius='16px'
          position='relative'
          shadow={2}
          mb='32px'
        >
          <Flex
            w='84px'
            py='10px'
            bg='#4B8660'
            direction='row'
            justifyContent='center'
            top='18px'
            borderRightRadius='8px'
            _text={{
              color: 'white',
            }}
          >
            制作期間
          </Flex>
        </Flex>
        <Flex w='100%' rounded='xl' mb='16px'>
          <Text fontSize='20px' bold alignSelf='flex-start' mb='16px'>
            サービス・アプリ開発
          </Text>
          <ScrollView horizontal>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
          </ScrollView>
        </Flex>
        <Flex w='100%' rounded='xl' mb='16px'>
          <Text fontSize='20px' bold alignSelf='flex-start' mb='16px'>
            ゲーム開発
          </Text>
          <ScrollView horizontal>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
          </ScrollView>
        </Flex>
        <Flex w='100%' rounded='xl' mb='16px'>
          <Text fontSize='20px' bold alignSelf='flex-start' mb='16px'>
            デザイン・イラスト
          </Text>
          <ScrollView horizontal>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
          </ScrollView>
        </Flex>
      </Flex>
    </ScrollView>
  )

  const ThirdRoute = () => (
    <ScrollView style={{ flex: 1 }}>
      <Flex direction='column' p='24px'>
        <Flex
          w='100%'
          h='226px'
          backgroundColor='gray.300'
          borderRadius='16px'
          position='relative'
          shadow={2}
          mb='32px'
        >
          <Flex
            w='84px'
            py='10px'
            bg='#000'
            direction='row'
            justifyContent='center'
            top='18px'
            borderRightRadius='8px'
            _text={{
              color: 'white',
            }}
          >
            終了期間
          </Flex>
        </Flex>
        <Flex w='100%' rounded='xl' mb='16px'>
          <Text fontSize='20px' bold alignSelf='flex-start' mb='16px'>
            サービス・アプリ開発
          </Text>
          <ScrollView horizontal>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
          </ScrollView>
        </Flex>
        <Flex w='100%' rounded='xl' mb='16px'>
          <Text fontSize='20px' bold alignSelf='flex-start' mb='16px'>
            ゲーム開発
          </Text>
          <ScrollView horizontal>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
          </ScrollView>
        </Flex>
        <Flex w='100%' rounded='xl' mb='16px'>
          <Text fontSize='20px' bold alignSelf='flex-start' mb='16px'>
            デザイン・イラスト
          </Text>
          <ScrollView horizontal>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
            <Flex
              w='128px'
              h='76px'
              bg='gray.300'
              borderRadius='16px'
              mr='24px'
              mb='16px'
            ></Flex>
          </ScrollView>
        </Flex>
      </Flex>
    </ScrollView>
  )

  const renderScene = SceneMap({
    first: FirstRoute,
    second: SecondRoute,
    third: ThirdRoute,
  })
  return (
    <TabView
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={setIndex}
      initialLayout={{ width: layout.width }}
      renderTabBar={(props) => (
        <TabBar
          {...props}
          style={{ backgroundColor: 'white' }}
          indicatorStyle={{ backgroundColor: 'blue' }}
          labelStyle={{ color: 'black' }}
        />
      )}
    />
  )
}

export default ProjectScreen
